config/routes.rb
Rails.application.routes.draw do

 devise_for :users
 root to: 'homes#top'
 get 'home/about' => 'homes#about'
 resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update,:index]
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user

    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: { maximum: 200 }

    has_many :book_comments, dependent: :destroy
    has_many :favorites, dependent: :destroy

    def favorited_by?(user)
      favorites.where(user_id: user.id).exists?
    end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :book_id, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments,dependent: :destroy

  attachment :profile_image

  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }


  def already_liked?(post)
    self.likes.exists?(book_id: post.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
     BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_to book_path(params[:book_id])
  end

   private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
    redirect_to book_path(@book.id),notice:'You have created book successfully.'
    else
      @user = current_user
      @books = Book.all
      render 'index'
    end
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all

  end

  def show
    @books = Book.all
    @showbook = Book.find(params[:id])
    @book = Book.new
    @user = @showbook.user
    @book_comment = BookComment.new
    @book_comments = @showbook.book_comments
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path ,notice:"Book was successfully destroyed."
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    redirect_to book_path(@book.id),notice:'Book was successfully updated.'
    else
    render 'edit'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

  private
    def correct_user
      book = Book.find(params[:id])
      if current_user.id != book.user_id
      redirect_to books_path
      end
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back fallback_location: books_path
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back fallback_location: books_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/profile_comments_controller.rb
class ProfileCommentsController < ApplicationController
  def create
    book = Book.find(params[:profile_image_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.profile_image_id = profile_image.id
    comment.save
    redirect_to book_path(book)
  end

  def destroy
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @currentuser = User.find(current_user.id)
  end

  def edit
    @user = User.find(params[:id])
    @books = @user.books
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user.id)
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id),notice:'You have updated book successfully.'
    else
      render 'edit'
    end
  end

  def index
    @user = User.find(current_user.id)
    @book = Book.new
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  private
  def correct_user
     user = User.find(params[:id])
     if current_user != user
       redirect_to user_path(current_user.id)
     end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
  <div class='container px-5 px-sm-0'>
  <div class='row'>
  <div class='col-md-3'>
  <h2>User info</h2>
  <table class='table'>
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <tbody>
  <tr>
	  <h6><th>name</th> <th><%= user.name %></th></h6>
  </tr>
  <tr>
	  <h6><th>introduction</th>  <th><%= user.introduction %></th></h6>
  </tr>
  </tbody>
  </table>

<div class='row'>
    <a><%= link_to "", edit_user_path(user),class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></a>
</div>
  <h2 class="mt-3">New book</h2>

  <%= form_with model:book, local:true do |f| %>
  <label>Title</label>
  <%= f.text_field :name, autofocus: true%>
  <label>Opinion</label>
  <%= f.text_area :body, autofocus: true%>
  <%= f.submit "Create Book" %>
<% end %>

app/views/books/edit.html.erb
<p id="notice"></p>
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  	<% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
  <%= form_with model:@book, local:true do |f| %>
  <div>
  <label>Title</label>
  <%= f.text_field :title, autofocus: true ,class: 'textbox' %>
  </div>
  <div>
  <label>Opinion</label>
  <%= f.text_area :body, autofocus: true ,class: 'textbox'%>
  </div>
  <%= f.submit 'Update Book', class: 'btn btn-sm btn-success'%>
  <% end %>

  <td><%=link_to 'Show', book_path(@book) %></td> |
  <td><%=link_to 'Back',"/books"%></td>

 </div>
  </div>
   </div>

app/views/books/index.html.erb
<main>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class='container px-5 px-sm-0'>
   <div class='row'>
<% if @book.errors.any? %>
    <h3><%= @book.errors.count %> error prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %></div></div></div>
  <div class='container px-5 px-sm-0'>
   <div class='row'>
    <div class='col-md-3'>
    <h2>User info</h2>
  <table class='table'>
  <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
  <tbody>
  <tr>
	  <h6><th>name</th> <th><%= @user.name %></th></h6>
  </tr>
  <tr>
	  <h6><th>introduction</th>  <th><%= @user.introduction %></th></h6>
  </tr>
  </tbody>
  </table>

<div class='row'>
    <a><%= link_to "", edit_user_path(@user),class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></a>
</div>
  <h2 class="mt-3">New book</h2>

  <%= form_with model:@book, local:true do |f| %>
  <label>Title</label>
  <%= f.text_field :title, autofocus: true,class: 'textbox'%>
  <label>Opinion</label>
  <%= f.text_area :body, autofocus: true,class: 'textbox'%>
  <%= f.submit "Create Book" %>
<% end %>
</div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
      <table class='table table-hover table-inverse'>
      <thead><tr>
      <th></th>
       <th>Title</th>
       <th>Opinion</th>
      </thead></tr>
    <% @books.each do |book| %>
    <tr>
      <th><%= link_to user_path(book.user) do %>
    <%= attachment_image_tag book.user, :profile_image,format: 'jpeg',fallback: "no_image.jpg",:size =>'50x60' %>
    <% end %>
      </th>
      <th>
          <%= link_to  book.title, book_path(book.id) %>
      </th>
      <th><%= book.body %></th>

      <% if book.favorited_by?(current_user) %>
      <th>
      <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, class: "fas fa-heart heart_red" %>
      </th>
      <% else %>
      <th>
        <%= link_to book.favorites.count, book_favorites_path(book), method: :post, class: "fas fa-heart" %>
      </th>
      <% end %>
      <th>
        <%=  "コメント数#{book.book_comments.count} " %>
      </th>

      </div>
    </tr>
    <% end %>
  </table>
      </div>
     </div>
    </div>
</main>

app/views/books/new.html.erb
Books

<main>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class='container px-5 px-sm-0'>
   <div class='row'>
<% if @book.errors.any? %>
    <h3><%= @book.errors.count %> errors prohibited this book from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %></div></div></div>
  <div class='container px-5 px-sm-0'>
   <div class='row'>
    <div class='col-md-3'>
    <h2>User info</h2>
  <table class='table'>
  <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" %>
  <tbody>
  <tr>
	  <h6><th>name</th> <th><%= @user.name %></th></h6>
  </tr>
  <tr>
	  <h6><th>introduction</th>  <th><%= @user.introduction %></th></h6>
  </tr>
  </tbody>
  </table>

<div class='row'>
    <a><%= link_to "", edit_user_path(@user),class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></a>
</div>
  <h2 class="mt-3">New book</h2>

  <%= form_with model:@book, local:true do |f| %>
  <label>Title</label>
  <%= f.text_field :title, autofocus: true%>
  <label>Opinion</label>
  <%= f.text_area :body, autofocus: true%>
  <%= f.submit "Create Book" %>
<% end %>
</div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
      <table class='table table-hover table-inverse'>
      <thead><tr>
      <th></th>
       <th>Title</th>
       <th>Opinion</th>
      </thead></tr>
    <% @books.each do |book| %>
    <tr>
      <th><%= attachment_image_tag @user, :profile_image, :fill, 30, 30, format: 'jpeg', fallback: "no_image.jpg" %>
      </th>
      <th>
          <%= link_to  book.name , book_path(book) %>
      </th>
      <th><%= book.body %></th>
      </div>
    </tr>
    <% end %>
  </table>
    </div>
    </div>
    </div>
</main>

app/views/books/show.html.erb
<p id="notice">
    <%=  notice %>
  <p>
  <div class='container px-5 px-sm-0'>
   <div class='row'>
    <div class='col-md-3'>
    <h2>User info</h2>
  <table class='table'>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <tbody>
  <tr>
	  <h6><th>name</th> <th><%= @user.name %></th></h6>
  </tr>
  <tr>
	  <h6><th>introduction</th>  <th><%= @user.introduction %></th></h6>
  </tr>
  </tbody>
  </table>

<div class='row'>
    <a><%= link_to "", edit_user_path(@user),class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></a>
</div>
  <h2 class="mt-3">New book</h2>

  <%= form_with model:@book, local:true do |f| %>
  <label>Title</label>
  <%= f.text_field :title, autofocus: true,class: 'textbox'%>
  <label>Opinion</label>
  <%= f.text_area :body, autofocus: true,class: 'textbox'%>
  <%= f.submit "Create Book", class: 'btn btn-sm btn-success'%>
  <% end %>
    </div>
     <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
  <table class='table table-hover table-inverse'>

      <th><%= link_to user_path(@user) do %>
  <%= attachment_image_tag @user, :profile_image,format: 'jpeg',fallback: "no_image.jpg",:size =>'40x50' %>
      <%= @user.name %>
      <% end %>
      </th>
      <th><%= link_to @showbook.title , book_path(@showbook.id) %></th>
      <th><%= @showbook.body %></th>
      <% if @user.id == current_user.id %>
      <th><%= link_to "Edit", edit_book_path(@showbook.id), class: 'btn btn-sm btn-success' %></th>
      <th><%= link_to "Destroy", book_path(@showbook.id), method: :delete ,"data-confirm" => "本当に削除しますか？" , class: 'btn btn-sm btn-danger' %></th>
      <% end %>

      <% if @showbook.favorited_by?(current_user) %>
      <th>
      <%= link_to @showbook.favorites.count, book_favorites_path(@showbook), method: :delete, class: "fas fa-heart heart_red" %>
      </th>
      <% else %>
      <th>
        <%= link_to @showbook.favorites.count, book_favorites_path(@showbook), method: :post, class: "fas fa-heart" %>
      </th>
      <% end %>
    </th>


    <th>コメント数：<%= @showbook.book_comments.count %></th>
    </table>

     <table>
     <% @book_comments.each do |book_comment| %>
     <tr>
     <td><%= link_to user_path(book_comment.user) do %>
      <%= attachment_image_tag book_comment.user, :profile_image,format: 'jpeg',fallback: "no_image.jpg",:size =>'40x50' %>
      <%= book_comment.user.name %></td>
      <% end %></td>
      <td><%= book_comment.comment %>
      <% if book_comment.user == current_user %>
       <%= link_to "Destroy", book_book_comment_path(book_comment.book,book_comment), method: :delete , class: 'btn btn-sm btn-danger' %></td>
      <% end %>
     <% end %>
      </tr>
      </table>
    <td>
    <%= form_with(model:[@showbook, @book_comment], local: true) do |f| %>
    <th><%= f.text_area :comment, rows:'5',placeholder: "コメントをここに",class: 'textbox' %></th>

    <th><%= f.submit "送信" %></th>
  <% end %>
        </td>
      </div>
   </div>
  </div>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
    <div class='container'>
  <div class='row'>
  <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
</main>

app/views/homes/top.html.erb
<main>
  <p id="notice">
    <%=  notice %>
  <p>
       <%#  <p id="notice">Signed out successfully.</p >%>
  <div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">

              <%= link_to "Sign up",new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>

        </div>
      </div>
    </div>
  </div>
</div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" "fas fa-home nav-link text-light" href="/">Bookers</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>

            <li>
              <%= link_to " Home", user_path(current_user), class: 'fas fa-home nav-link text-light' %>
            </li>
            <li>
              <%= link_to " Users", users_path, class: 'fas fa-users nav-link text-light' %>
            </li>
            <li>
              <%= link_to " Books", books_path, class: 'fas fa-book-open nav-link text-light' %>
            </li>
            <li>
              <%= link_to " logout", destroy_user_session_path, method: :delete, notice:'You have created book successfully.',class: 'fas fa-sign-out-alt nav-link text-light' %>
            </li>


            <% else %>
            <li>
              <a class="fas fa-home nav-link text-light" href="/"> Home</a>
            </li>
            <li><a class="fas fa-link nav-link text-light" href="/home/about"> About</a></li>
            <li class="nav-item">
              <li><a class="fas fa-user-plus nav-link text-light" href="/users/sign_up"> sign up</a></li>
            </li>
            <li class="nav-item">
              <li><a class="fas fa-sign-in-alt nav-link text-light" href="/users/sign_in"> login</a></li></li>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
    <%= yield %>
    </main>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
         <p> CopyRight Infratop.inc </p>
         </div>
        </div>
      </div>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
<h2>User info</h2>
<% if @user.errors.any? %>
    <h3><%= @user.errors.count %> errors prohibited this book from being saved:</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<%= form_with model:@user, local:true do |f| %>
  <div class="form-group">
  　<label for="user_name">Name</label>
  </div>
  <div class="form-group">
  　<%= f.text_field :name, autofocus: true, placeholder:"名前"%>
  </div>
  <div class="form-group">
  　<label for="user_image">Image</label>
  　<%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  </div>
  <div class="form-group">
  　<label for="user_introduction">introduction</label>
  </div>
  <div class="form-group">
  　<%= f.text_area :introduction, autofocus: true%>
  </div>
  　<a><%= f.submit "Update User"%></a>
  </div>
<% end %>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
   <div class='row'>
   <div class='col-md-3'>
     <p id="notice"></p>
    <h2>User info</h2>
  <table class='table'>
  <th><%= attachment_image_tag @user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", :size =>'50x60'%>
  <tbody>
  <tr>
	  <h6><th>name</th> <th><%= @user.name %></th></h6>
  </tr>
  <tr>
	  <h6><th>introduction</th>  <th><%= @user.introduction %></th></h6>
  </tr>
  </tbody>
  </table>

<div class='row'>
  <% if @user.id == current_user.id %>
    <a><%= link_to "", edit_user_path(@user),class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></a>
  <% end %>
</div>
  <h2 class="mt-3">New book</h2>

  <%= form_with model:@book, local:true do |f| %>
  <label>Title</label>
  <%= f.text_field :title, autofocus: true,class: 'textbox'%>
  <label>Opinion</label>
  <%= f.text_area :body, autofocus: true,class: 'textbox'%>
  <%= f.submit "Create Book", class: 'btn btn-sm btn-success'%>
  <% end %>
    </div>
     <div class='col-md-8 offset-md-1'>
       <p></p>
      <h2>Users</h2>
  <table class='table'>
      <thead><tr>
       <th>image</th>
       <th>name</th>
      </thead></tr>
    <% @users.each do |user| %>
    <tr>
      <th><%= attachment_image_tag user, :profile_image, format: 'jpeg', fallback: "no_image.jpg",:size =>'50x60' %></th>
      <th><%= user.name %></th>
      <th><th>
          <%= link_to "Show", user_path(user.id) %>
      </th></th>
      </div>
    </tr>
    <% end %>
  </table>
    </div>
  </div>

app/views/users/show.html.erb
<main>
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
  <div class='container px-5 px-sm-0'>
   <div class='row'>
    <div class='col-md-3'>
    <h2>User info</h2>
  <table class='table'>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <tbody>
  <tr>
	  <h6><th>name</th> <th><%= @user.name %></th></h6>
  </tr>
  <tr>
	  <h6><th>introduction</th>  <th><%= @user.introduction %></th></h6>
  </tr>
  </tbody>
  </table>

<div class='row'>
    <a><%= link_to "", edit_user_path(@user),class: 'btn btn-outline-secondary btn-block fas fa-user-cog' %></a>
</div>
  <h2 class="mt-3">New book</h2>

  <%= form_with model:@book, local:true do |f| %>
  <label>Title</label>
  <%= f.text_field :title, autofocus: true,class: 'textbox'%>
  <label>Opinion</label>
  <%= f.text_area :body, autofocus: true,class: 'textbox'%>
  <%= f.submit "Create Book" %>
<% end %>
</div>
      <div class='col-md-8 offset-md-1'>
        <h2>Books</h2>
      <table class='table table-hover table-inverse'>
      <thead><tr>
      <th></th>
       <th>Title</th>
       <th>Opinion</th>
      </thead></tr>
    <% @books.each do |book| %>
    <tr>
      <th><%= link_to user_path(@user) do %>
    <%= attachment_image_tag @user, :profile_image,format: 'jpeg',fallback: "no_image.jpg",:size =>'50x60' %>
    <% end %>
      </th>
      <th>
          <%= link_to  book.title , book_path(book) %>
      </th>
      <th><%= book.body %></th>
      <% if book.favorited_by?(current_user) %>
      <th>
      <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, class: "fas fa-heart heart_red" %>
      </th>
      <% else %>
      <th>
        <%= link_to book.favorites.count, book_favorites_path(book), method: :post, class: "fas fa-heart" %>
      </th>
      <% end %>
      <th>
        <%=  "コメント数#{book.book_comments.count} " %>
      </th>
    </tr>
    <% end %>
  </table>
      </div>
     </div>
    </div>
</main>